### ISSUE TITLE
SiteUrl Is an external Link and it is being used as the to property of Link component which results in 404.

### ISSUE THREAD

**Issue by kutty-kumar** [GeeksCreed/geekscreed.com#1]
In blog-post.js at line number 251 where the floating header is being displayed, should we replace the Link Tag with an anchor tag ?

**Comment by sasivarnan** [comment]
Thanks for your time to share about this issue. 

I have fixed it and published a new version of the theme today - https://github.com/sasivarnan/gatsby-theme-ghost-casper/commit/75138a1a1e6b820f2b62a20398333b3e8d2bb921
